In [23]:
import pandas as pd 
import numpy as np
from sklearn import linear_model


In [24]:
df = pd.read_csv("./data/housePriceM.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [25]:
median_bedroom = np.floor(df.bedrooms.median())
median_bedroom

3.0

In [26]:
df.bedrooms = df.bedrooms.fillna(median_bedroom)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [27]:
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms', 'age']].values, df.price.values)

LinearRegression()

In [28]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [29]:
reg.intercept_

383724.99999999994

In [32]:
reg.predict([[3000, 3,40]])

array([444400.])

In [33]:
reg.predict([[2500, 4,5]])

array([588625.])