In [148]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [149]:
df = pd.read_csv("./data/hiring.csv")
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [150]:
df.experience = df.experience.fillna("zero")
df.head()


experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [151]:
from word2number import w2n
# pd.options.mode.chained_assignment = None
# for i in range(df.experience.shape[0]):
#     print(df.experience[i])
#     df.experience[i] = w2n.word_to_num(df.experience[i])
df.experience = df.experience.apply(w2n.word_to_num)
df.head()
    

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000

In [152]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [160]:
median_test_score = np.floor(df['test_score(out of 10)']. mean())
print(median_test_score)
df[df.columns[1]] = df[df.columns[1]].fillna(median_test_score)
df

7.0


experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [154]:
reg = linear_model.LinearRegression()
reg.fit(df[[df.columns[0],df.columns[1], df.columns[2]]].values, df[df.columns[3]].values)

LinearRegression()

In [155]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [156]:
reg.intercept_

17737.263464337688

In [157]:
reg.predict([[2,9,6]])

array([53205.96797671])

In [158]:
reg.predict([[12,10,10]])

array([92002.18340611])